# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: digital-prison-reporting-mi-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    REDSHIFT_JDBC_URL: jdbc:redshift://dpr-redshift-development.ctf9dwuxkfvc.eu-west-2.redshift.amazonaws.com:5439/datamart
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk

  allowlist:
    groups:
      - circleci
      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-dev
