---
# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  ingress:
    host: digital-prison-reporting-mi.hmpps.service.justice.gov.uk
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk
    DEFINITIONS_HOST: http://hmpps-dpr-data-product-definitions-prod.hmpps-digital-prison-reporting-mi-prod.svc.cluster.local

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-prod
