---
# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: digital-prison-reporting-mi-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk
    DEFINITIONS_HOST: http://hmpps-dpr-data-product-definitions-preprod.hmpps-digital-prison-reporting-mi-preprod.svc.cluster.local
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-preproduction
    REDSHIFT_DATA_DB: datamart
    REDSHIFT_DATA_ROLE_ARN: arn:aws:iam::972272129531:role/dpr-data-api-cross-account-role

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-preprod
