# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  replicaCount: 2
  serviceAccountName: "dpr-reporting-mi-development-cross-iam"

  ingress:
    host: digital-prison-reporting-mi-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
    DEFINITIONS_HOST: http://hmpps-dpr-data-product-definitions-dev.hmpps-digital-prison-reporting-mi-dev.svc.cluster.local
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-development
    REDSHIFT_DATA_DB: datamart
    REDSHIFT_DATA_ROLE_ARN: arn:aws:iam::771283872747:role/dpr-redshift-data-api-cross-role-development

  allowlist:
    groups:
      - circleci
      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-dev
